### ISSUE TITLE
documentation: switch to restructured text

### ISSUE THREAD

**Issue by wdpypere** [quattor/documentation#4]
markdown was chosen because this was originally hosted on quattor.org. Now we have readthedocs we should switch to rst because the md features are limited. Especially for sidebar/menu control, interlinking, etc rst/readthedocs has superior features. 
And with the addition of CCM, grid, CAF, ... some collapsing and other control will be welcome.

**Comment by jrha** [comment]
@wdpypere I seem to recall that you had written some code for this... perhaps at the Annecy workshop?

**Comment by jrha** [comment]
https://github.com/wdpypere/release/tree/rst?

**Comment by stdweird** [comment]
@jrha @wdpypere is back next week

**Comment by jrha** [comment]
cool
